<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260704223236 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée les tables use_category/use_item, reprend le contenu de config/uses.yaml (supprimé)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE use_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_fr VARCHAR(255) NOT NULL, name_en VARCHAR(255) NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE use_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_fr VARCHAR(255) NOT NULL, name_en VARCHAR(255) NOT NULL, value_fr VARCHAR(255) NOT NULL, value_en VARCHAR(255) NOT NULL, position INT NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8037B6DA12469DE2 ON use_item (category_id)');
        $this->addSql('ALTER TABLE use_item ADD CONSTRAINT FK_8037B6DA12469DE2 FOREIGN KEY (category_id) REFERENCES use_category (id) NOT DEFERRABLE');

        // Reprise du contenu de config/uses.yaml (supprimé au profit de ces tables)
        $this->addSql(<<<'SQL'
            INSERT INTO use_category (name_fr, name_en, position) VALUES
                ('Éditeur & terminal', 'Editor & terminal', 1),
                ('Stack de prédilection', 'Preferred stack', 2),
                ('Matériel', 'Hardware', 3),
                ('Hébergement & infra', 'Hosting & infra', 4)
            SQL);

        $this->addSql(<<<'SQL'
            INSERT INTO use_item (category_id, name_fr, name_en, value_fr, value_en, position) VALUES
                ((SELECT id FROM use_category WHERE name_fr = 'Éditeur & terminal'), 'Éditeur', 'Editor', 'Placeholder — à remplacer (ex. Neovim, VS Code…)', 'Placeholder — fill in (e.g. Neovim, VS Code…)', 1),
                ((SELECT id FROM use_category WHERE name_fr = 'Éditeur & terminal'), 'Terminal', 'Terminal', 'Placeholder', 'Placeholder', 2),
                ((SELECT id FROM use_category WHERE name_fr = 'Éditeur & terminal'), 'Shell', 'Shell', 'Placeholder (zsh, fish…)', 'Placeholder (zsh, fish…)', 3),
                ((SELECT id FROM use_category WHERE name_fr = 'Stack de prédilection'), 'Backend', 'Backend', 'Symfony, PHP', 'Symfony, PHP', 1),
                ((SELECT id FROM use_category WHERE name_fr = 'Stack de prédilection'), 'Frontend', 'Frontend', 'Tailwind CSS, Stimulus', 'Tailwind CSS, Stimulus', 2),
                ((SELECT id FROM use_category WHERE name_fr = 'Stack de prédilection'), 'Base de données', 'Database', 'PostgreSQL', 'PostgreSQL', 3),
                ((SELECT id FROM use_category WHERE name_fr = 'Matériel'), 'Machine', 'Machine', 'Placeholder', 'Placeholder', 1),
                ((SELECT id FROM use_category WHERE name_fr = 'Matériel'), 'Clavier', 'Keyboard', 'Placeholder', 'Placeholder', 2),
                ((SELECT id FROM use_category WHERE name_fr = 'Hébergement & infra'), 'Serveur', 'Server', 'FrankenPHP', 'FrankenPHP', 1),
                ((SELECT id FROM use_category WHERE name_fr = 'Hébergement & infra'), 'CI/CD', 'CI/CD', 'Placeholder', 'Placeholder', 2)
            SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE use_item DROP CONSTRAINT FK_8037B6DA12469DE2');
        $this->addSql('DROP TABLE use_category');
        $this->addSql('DROP TABLE use_item');
    }
}
