<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260704221412 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée les tables profile/hub_link, reprend le contenu de config/hub.yaml (supprimé)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE hub_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label_fr VARCHAR(255) NOT NULL, label_en VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, icon VARCHAR(32) NOT NULL, accent VARCHAR(16) NOT NULL, external BOOLEAN NOT NULL, description_fr VARCHAR(255) NOT NULL, description_en VARCHAR(255) NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, tagline_fr VARCHAR(255) NOT NULL, tagline_en VARCHAR(255) NOT NULL, bio_fr TEXT NOT NULL, bio_en TEXT NOT NULL, banner VARCHAR(255) DEFAULT NULL, logo VARCHAR(255) NOT NULL, PRIMARY KEY (id))');

        // Reprise du contenu de config/hub.yaml (supprimé au profit de ces tables)
        $this->addSql(<<<'SQL'
            INSERT INTO profile (name, tagline_fr, tagline_en, bio_fr, bio_en, banner, logo)
            VALUES (
                'PetrosLabs',
                'discipline antique, code moderne',
                'ancient discipline, modern code',
                'Ici, la rigueur spartiate rencontre le code d''aujourd''hui, entre colonnes de marbre et lueurs de terminal. Bienvenue au laboratoire.',
                'Here, Spartan discipline meets modern code, between marble columns and the glow of a terminal. Welcome to the lab.',
                'images/banner.png',
                'images/logo.png'
            )
            SQL);

        $this->addSql(<<<'SQL'
            INSERT INTO hub_link (label_fr, label_en, url, icon, accent, external, description_fr, description_en, position)
            VALUES
                ('GitHub', 'GitHub', 'https://github.com/petroslabs', 'github', 'teal', true, 'Le code, brut', 'The raw code', 1),
                ('Email', 'Email', 'mailto:petroslabs@proton.me', 'mail', 'bronze', false, 'Écris-moi', 'Write to me', 2),
                ('Blog', 'Blog', '/blog', 'blog', 'teal', false, 'Notes du laboratoire', 'Lab notes', 3),
                ('Projets', 'Projects', '/projects', 'projects', 'bronze', false, 'Ce que je construis', 'What I build', 4),
                ('L''établi', 'The workbench', '/uses', 'uses', 'teal', false, 'Les outils du labo', 'The tools of the lab', 5),
                ('LinkedIn', 'LinkedIn', '#', 'linkedin', 'bronze', true, 'Le parcours', 'My background', 6)
            SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE hub_link');
        $this->addSql('DROP TABLE profile');
    }
}
