<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260704224603 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée la table blog_post, reprend le contenu de content/blog/*.md (supprimés)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE blog_post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) NOT NULL, title_fr VARCHAR(255) NOT NULL, title_en VARCHAR(255) NOT NULL, summary_fr VARCHAR(255) NOT NULL, summary_en VARCHAR(255) NOT NULL, content_fr TEXT NOT NULL, content_en TEXT NOT NULL, cover VARCHAR(255) DEFAULT NULL, date DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BA5AE01D989D9B62 ON blog_post (slug)');

        // Reprise du contenu de content/blog/bienvenue.{fr,en}.md (supprimés au profit de cette table)
        $this->addSql(<<<'SQL'
            INSERT INTO blog_post (slug, title_fr, title_en, summary_fr, summary_en, content_fr, content_en, cover, date)
            VALUES (
                'bienvenue',
                'Bienvenue au laboratoire',
                'Welcome to the lab',
                'Premier mot depuis l''atelier : pourquoi ce blog, et ce qu''il devrait devenir.',
                'First word from the workshop: why this blog exists, and what it should become.',
                'Bienvenue sur le blog de PetrosLabs.

            Cet espace accueillera des notes sur ce qui se construit ici : quelques
            retours d''expérience, des choix techniques disséqués, et sans doute plus
            tard des réflexions moins strictement techniques. Pas de calendrier
            éditorial fixe — les billets viendront au rythme du laboratoire, quand il y
            aura quelque chose qui mérite d''être écrit noir sur blanc plutôt que gardé
            pour soi.

            À bientôt.',
                'Welcome to the PetrosLabs blog.

            This space will host notes on what gets built here: a few experience
            reports, some technical choices dissected, and probably later some less
            strictly technical thoughts. No fixed editorial calendar — posts will come
            at the lab''s own pace, whenever something is worth writing down rather than
            kept to myself.

            See you soon.',
                NULL,
                '2026-07-04'
            )
            SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE blog_post');
    }
}
