<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260704214954 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée les tables project/user, reprend le contenu de config/projects.yaml (supprimé)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, summary_fr TEXT NOT NULL, summary_en TEXT NOT NULL, image VARCHAR(255) NOT NULL, stack JSON NOT NULL, status VARCHAR(32) NOT NULL, repo_url VARCHAR(255) DEFAULT NULL, demo_url VARCHAR(255) DEFAULT NULL, position INT NOT NULL, PRIMARY KEY (id))');

        // Reprise du contenu de config/projects.yaml (supprimé au profit de cette table)
        $this->addSql(<<<'SQL'
            INSERT INTO project (name, summary_fr, summary_en, image, stack, status, repo_url, demo_url, position)
            VALUES (
                'PetrosLabs',
                'Ce site : un hub Symfony reliant blog, projets et réseaux, avec une direction artistique entre Grèce antique et laboratoire de dev moderne.',
                'This site: a Symfony hub linking blog, projects and social links, with an art direction between ancient Greece and a modern dev lab.',
                'images/projects/project-1.webp',
                '["Symfony", "Tailwind CSS v4", "AssetMapper"]',
                'in_progress',
                'https://github.com/petroslabs/portfolio',
                NULL,
                1
            )
            SQL);

        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
